name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
        contents: write

    steps:
          - name: Checkout source code
            uses: actions/checkout@v7

          - name: Extract version number from Cargo.toml
            id: version
            shell: bash
            run: |
              echo "version=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)".*/\1/')" >> $GITHUB_OUTPUT

          - name: Install Rust toolchain
            uses: dtolnay/rust-toolchain@stable

          - name: Build release binary
            run: cargo build --release

          - name: Package release
            shell: bash
            run: |
              mkdir shp_decoder
              cp target/release/shp_decoder.exe shp_decoder/
              7z a shp_decoder.zip ./shp_decoder
          
          - name: Create GitHub Release
            uses: softprops/action-gh-release@v3
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              name: Shp Decoder v${{ steps.version.outputs.version }}
              tag_name: v${{ steps.version.outputs.version }}
              files: target/release/shp_decoder.exe
              prerelease: false
              body: |
                ## 🔧 更新内容

                - 添加serde和serde_json来实现json读取,最终会在同级别目录生成一个config.json
                - 文件,用来保存需要存储的数据
                - 所有数据都能够存储,下次不用重新选择
                - 添加config.rs文件定义config数据结构
                - 添加全局变量保存退出订阅和数据单例
                - 为exe外层包裹一个文件夹

                ## 📦 发布说明

                - 当前版本: v${{ steps.version.outputs.version }}
